"""Shared defaults and runtime constants for one day-run orchestration."""

from day_cycle_simulation.models import SyntheticSessionGenerationConfig

from .day_cycle import (
    DEFAULT_DAY_CYCLE_BIN_WORKERS,
    DEFAULT_DAY_CYCLE_LOAD_CURVE_CSV,
    DEFAULT_SYNTHETIC_SESSION_GENERATION_CONFIG,
)


DEFAULT_DAY_RUN_CORES = DEFAULT_DAY_CYCLE_BIN_WORKERS
DEFAULT_DAY_RUN_LOAD_CURVE_CSV = DEFAULT_DAY_CYCLE_LOAD_CURVE_CSV
DEFAULT_DAY_RUN_SESSION_GENERATION_CONFIG = DEFAULT_SYNTHETIC_SESSION_GENERATION_CONFIG

THREAD_LIMIT_ENV_VARS = (
    "OMP_NUM_THREADS",
    "MKL_NUM_THREADS",
    "OPENBLAS_NUM_THREADS",
    "NUMEXPR_NUM_THREADS",
)
WORKER_LOG_LEVEL_ENV_VAR = "THESIS_RUN_LOG_LEVEL"
ACTIVE_BIN_SCOPE_ENV_VAR = "THESIS_ACTIVE_BIN_SCOPE"

LOG_LEVEL_CHOICES = ("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL")
PROGRESS_LOG_INTERVAL = 8
DAY_RUN_RESULT_FILENAME = "day_run_result.json"


__all__ = [
    "ACTIVE_BIN_SCOPE_ENV_VAR",
    "DAY_RUN_RESULT_FILENAME",
    "DEFAULT_DAY_RUN_CORES",
    "DEFAULT_DAY_RUN_LOAD_CURVE_CSV",
    "DEFAULT_DAY_RUN_SESSION_GENERATION_CONFIG",
    "LOG_LEVEL_CHOICES",
    "PROGRESS_LOG_INTERVAL",
    "SyntheticSessionGenerationConfig",
    "THREAD_LIMIT_ENV_VARS",
    "WORKER_LOG_LEVEL_ENV_VAR",
]
